### ISSUE TITLE
python3 support plan?

### ISSUE THREAD

**Issue by phuslu** [dlecocq/nsq-py#48]
Hi @dlecocq

Thanks for this python lib! It helps a lot. 👍 
And any thoughts about python3 support?

Thanks,
Phus

**Comment by dlecocq** [comment]
Hi Phus,

Sorry for the delayed response. I currently have no plans for support for Python 3, but I certainly welcome it. I don't imagine there will be too many problems in doing so -- there's some string manipulation, but in general I write code that things of strings as bytestrings, which usually makes the translation more rote.

If you're interested, I'd recommend forking it and seeing how you can get with setting `.python-version` to something 3.2+ (I can't remember which 3 version chronically causes problems -- IIRC it's 3.1 or 3.2, but whichever one it is, we should skip it) and start working down the list of problems. A module like `six` would probably be really helpful.

One thing any effort on this front should be careful of is to preserve the current performance, so running the benchmarking profile (https://github.com/dlecocq/nsq-py/blob/master/shovel/profile.py) should be part of the evaluation process.

- D

**Comment by asottile** [comment]
please try out the patch in #52!
